name: CI backend project

on:
  push:
    branches:
      - "main"
jobs:
  build_portal:
    name: Build portal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "npm"
          cache-dependency-path: "./portal/package-lock.json"
      - name: Install deps
        run: npm ci && npm i jquery --save
        working-directory: ./portal
      - name: Lint project
        run: npm run lint
        working-directory: ./portal
      - name: Build app
        run: npm run build:prod
        working-directory: ./portal

  build_api:
    name: Build API
    runs-on: ubuntu-latest
    needs: [build_portal]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          check-latest: true
      - name: Build project
        run: mvn clean install -DskipTests
        working-directory: ./technical-assignment
      - name: Test project
        run: mvn test
        working-directory: ./technical-assignment
